version = 1
SPDX-PackageName = "technologydata"
SPDX-PackageSupplier = "technologydata contributors"
SPDX-PackageDownloadLocation = "https://github.com/open-energy-transition/technology-data"

[[annotations]]
path = ["uv.lock", "*.yaml", "docs/**", "*.md", "*.in"]
SPDX-FileCopyrightText = "technologydata contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["test/test_data/**"]
SPDX-FileCopyrightText = "technologydata contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "src/technologydata/parsers/dea_energy_storage/*.json", "src/technologydata/parsers/schemas/*.json", "src/technologydata/parsers/raw/manual_input_usa.csv", "src/technologydata/parsers/manual_input_usa/*.json",
]
SPDX-FileCopyrightText = "technologydata contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "src/technologydata/parsers/raw/Technology_datasheet_for_energy_storage.xlsx"
]
SPDX-FileCopyrightText = "The Danish Energy Agency"
SPDX-License-Identifier = "CC-BY-4.0"
